#!/usr/bin/env python3
"""Rebuild insurance_lexicon.json.

The day-one corpus is generated by the inline builder used during setup.
Prefer re-running the generation command documented in docs if regenerating.

  cd /path/to/customer_feedback_platform
  .venv/bin/python -c "print('Use repo generation script from agent session / CI artifact')"
"""

from pathlib import Path
import json

DATA = Path(__file__).resolve().parents[1] / "app" / "data" / "insurance_lexicon.json"


def main() -> None:
    if not DATA.exists():
        raise SystemExit(f"Missing {DATA}; regenerate via project lexicon builder.")
    data = json.loads(DATA.read_text(encoding="utf-8"))
    print(f"{DATA}: {data.get('entry_count')} entries, version={data.get('version')}")


if __name__ == "__main__":
    main()
